### ISSUE TITLE
BitTorrent protocol doesn't work over WebRTC

### ISSUE THREAD

**Issue by YIFYtorrents** [KeizerDev/Browsertime#4]
It's not yet possible to use the WebRTC for the BitTorrent protocol. Read this: https://github.com/feross/webtorrent/issues/39

The problem is YIFY uses BitTorrent and not WebRTC. How you gonna solve the problem?

**Comment by KeizerDev** [comment]
Yeah, but it is possible with a tracker to port it to it's other protocol. We just need another tracker for it. Nothing more

**Comment by YIFYtorrents** [comment]
Does WebRTC also support DHT ? BTW I can setup a tracker, I have the resources. Can you open a chat room for this repo?

**Comment by alxhotel** [comment]
WebTorrent can not "talk with" a BitTorrent client, for now.

Don't know what "a tracker to port to it's other protocol" means, but I think you should take a different approach

**Comment by KeizerDev** [comment]
@alxhotel @YIFYtorrents Check out this issue https://github.com/feross/webtorrent/issues/466

**Comment by KeizerDev** [comment]
@YIFYtorrents I've added a chat. If you want to talk secretly you should mail me first and we will talk about the opportunities. BTW, you can have a private conversation on Gitter!

**Comment by KeizerDev** [comment]
We can use https://github.com/feross/webtorrent-hybrid to make it all work!
Check out this image: 
![The protocol](https://camo.githubusercontent.com/3f57ad9ba26fad961f316c2eb20d5b9f12341b6e/68747470733a2f2f776562746f7272656e742e696f2f696d672f6e6574776f726b2e706e67)

**Comment by alxhotel** [comment]
Sure.

Btw, if we want this project to have a long life, we should stay away from copyright infringement. At least, until we have something useful.

Don't you think? @KeizerDev

**Comment by KeizerDev** [comment]
@alxhotel True, I can make some private repo's, but I first need more devs who are willing to spend time on it.
